### ISSUE TITLE
[FR]: @bazel/runfiles needs to handle repo mapping

### ISSUE THREAD

**Issue by jfirebaugh** [bazel-contrib/rules_nodejs#3714]
### What is the current behavior?

The @bazel/runfiles library fails to find runfiles specified with apparent repository names when Bzlmod is enabled.

### Describe the feature

Equivalent to https://github.com/bazelbuild/rules_go/pull/3347 / https://github.com/bazelbuild/rules_python/pull/998.

**Comment by alexeagle** [comment]
@fmeum I know you visited a lot of languages in the ecosystem for the other runfiles fixes. I don't recall, did you have a look here as well?

**Comment by fmeum** [comment]
The lookup procedure itself looks sound. It's really just the repo mapping logic that is missing.

My JS is pretty rusty, so I would prefer someone else to implement this, but I can review the PR. The Python library can serve as a reference here. 

The challenging part would be determining the current repo. I don't know how one would get the path of the current source file in JS. Minification and bundling could be problematic in this context. Can source maps be consumed at runtime?

**Comment by alexeagle** [comment]
@ewhauser is this something you're interested in pairing with Fabian on?

**Comment by jfirebaugh** [comment]
Can someone please add a label to turn off the stale bot for this issue? This blocks use of bzlmod for anyone using `@bazel/runfiles` so it's not going to go stale.

**Comment by jfirebaugh** [comment]
*sigh* Not stale.

**Comment by gregmagolan** [comment]
I'm tempted to move the implementation of the runfiles library to rules_js at this point in the process of fixing it for bzlmod. rules_nodejs now only supplies the Node.js toolchain and no longer deals with the runtime js_binary / js_test implementation. I'm not sure we even have the right permissions to publish to the `@bazel/runfiles` npm package.

**Comment by jbedard** [comment]
Fixed in https://github.com/bazel-contrib/rules_nodejs/commit/21b56da9f20c9c5e8b8c1ac19052f1f7cc7b5920
