### ISSUE TITLE
[Bug]: Documentation link broken

### ISSUE THREAD

**Issue by tinkerbeast** [bazel-contrib/rules_nodejs#3792]
### What happened?

Following https://bazelbuild.github.io/rules_nodejs/ leads to error page.

### Version

Documentation error, not bazel related.

**Comment by gregmagolan** [comment]
Thanks for reporting. I believe the broken link was in rules_js. Fixed there now. It would be helpful for maintainers to also link to where the link was broken or put up PR fix the fix.

**Comment by gregmagolan** [comment]
For reference, the link was broken because rules_nodejs was donated by Google to the Linux foundation and it moved from the bazelbuild GitHub org to bazel-contrib. Looks like GitHub doesn't re-direct for these. New docs URL is https://bazel-contrib.github.io/rules_nodejs/
