### ISSUE TITLE
[Bug]: Please release the rules with support for Node 22 at least :)

### ISSUE THREAD

**Issue by maapteh** [bazel-contrib/rules_nodejs#3801]
### What happened?

I can not upgrade my repository while this Node version has tons of extra's to make my code cleaner. Master has this version https://github.com/bazel-contrib/rules_nodejs/blob/main/nodejs/private/node_versions.bzl#L2947-L2953 it just needs an official release from your library :)

### Version

Development (host) and target OS/architectures:

❯ bazel --version
bazel 7.4.0rc1

Version of rules_nodejs: 6.3.1

**Comment by alexeagle** [comment]
```
% git push origin v6.3.2
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To github.com:bazel-contrib/rules_nodejs.git
 * [new tag]           v6.3.2 -> v6.3.2
 ```
